In [1]:
import numpy as np

## Data Type and Attributes

In [2]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6]],
               [[7, 8, 9],
                [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 18]],
               [[18,20,21],
               [22,23,24]]
              ])

In [3]:
a3.shape

(4, 2, 3)

In [4]:
a3.ndim

3

In [5]:
a3.dtype

dtype('int32')

In [6]:
a3.size

24

In [7]:
# Creating a DataFrame from Numpy array
#import pandas as pd

#df = pd.DataFrame(a3)
#df

In [8]:
type(a3)

numpy.ndarray

## Creating arrays

In [9]:
sample_arr = np.array([1,2,3])
sample_arr

array([1, 2, 3])

In [10]:
sample_arr.dtype

dtype('int32')

In [11]:
ones = np.ones((2,3))

In [12]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
range_array = np.arange(0 ,10, 2)
range_array

array([0, 2, 4, 6, 8])

In [15]:
random_array = np.random.randint(0 , 10, size = (3,4))
random_array

array([[3, 5, 7, 9],
       [6, 9, 2, 9],
       [6, 2, 6, 8]])

In [16]:
# Pseudo random numbers
np.random.seed(5)
random_array = np.random.randint(0 , 10, size = (3,4))
random_array

array([[3, 6, 6, 0],
       [9, 8, 4, 7],
       [0, 0, 7, 1]])

## Viewing arrays and matrices

In [17]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[18, 20, 21],
        [22, 23, 24]]])

In [18]:
a3[1][0]

array([7, 8, 9])

In [19]:
a3.shape

(4, 2, 3)

In [20]:
a3[:3 ,:1 ,:2]

array([[[ 1,  2]],

       [[ 7,  8]],

       [[13, 14]]])

In [21]:
np.random.seed(5)
a4 = np.random.randint(10 , size = (2,3,4,5))
a4

array([[[[3, 6, 6, 0, 9],
         [8, 4, 7, 0, 0],
         [7, 1, 5, 7, 0],
         [1, 4, 6, 2, 9]],

        [[9, 9, 9, 1, 2],
         [7, 0, 5, 0, 0],
         [4, 4, 9, 3, 2],
         [4, 6, 9, 3, 3]],

        [[2, 1, 5, 7, 4],
         [3, 1, 7, 3, 1],
         [9, 5, 7, 0, 9],
         [6, 0, 5, 2, 8]]],


       [[[6, 8, 0, 5, 2],
         [0, 7, 7, 6, 0],
         [0, 8, 5, 5, 9],
         [6, 4, 5, 2, 8]],

        [[8, 1, 6, 3, 4],
         [1, 8, 0, 2, 2],
         [4, 1, 6, 3, 4],
         [3, 1, 4, 2, 3]],

        [[4, 9, 4, 0, 6],
         [6, 9, 2, 9, 3],
         [0, 8, 8, 9, 7],
         [4, 8, 6, 8, 0]]]])

In [22]:
a4[: , :2 , :3 , :3][1]

array([[[6, 8, 0],
        [0, 7, 7],
        [0, 8, 5]],

       [[8, 1, 6],
        [1, 8, 0],
        [4, 1, 6]]])

## Manipulating and comparing arrays

### Arithmetic

### Aggregation

In [23]:
list1 = [2,4,6]
list1

[2, 4, 6]

In [24]:
sum(list1)

12

In [25]:
np.sum(list1)

12

In [26]:
# Creating a massive Numpy array
massive_array = np.random.random(100000)
massive_array.size

100000

In [27]:
massive_array[:10]

array([0.80140153, 0.0539621 , 0.19047777, 0.45241885, 0.70294208,
       0.33204815, 0.3599832 , 0.92147057, 0.95363051, 0.40768573])

In [28]:
%timeit sum(massive_array) #Python's sum()
%timeit np.sum(massive_array) # NumPy's sum()

11.6 ms ± 26.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
66.3 µs ± 620 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [29]:
a2 = np.array([[1.,2.,3.3],
               [4.,5.,6.5]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [30]:
np.mean(a2)

3.6333333333333333

In [31]:
#Higher varianve = wider range of numebers
#Lower variance = Lower range of numbers

In [32]:

#Demo of std and var

### Reshaping and Transposing

In [33]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [34]:
a2.shape

(2, 3)

In [35]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[18, 20, 21],
        [22, 23, 24]]])

In [36]:
a3.shape

(4, 2, 3)

In [37]:
a2 * a3

array([[[  1. ,   4. ,   9.9],
        [ 16. ,  25. ,  39. ]],

       [[  7. ,  16. ,  29.7],
        [ 40. ,  55. ,  78. ]],

       [[ 13. ,  28. ,  49.5],
        [ 64. ,  85. , 117. ]],

       [[ 18. ,  40. ,  69.3],
        [ 88. , 115. , 156. ]]])

In [38]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[18, 20, 21],
        [22, 23, 24]]])

In [39]:
a3.shape

(4, 2, 3)

In [40]:
a3.T

array([[[ 1,  7, 13, 18],
        [ 4, 10, 16, 22]],

       [[ 2,  8, 14, 20],
        [ 5, 11, 17, 23]],

       [[ 3,  9, 15, 21],
        [ 6, 12, 18, 24]]])

In [41]:
a3.T.shape

(3, 2, 4)

In [42]:
np.random.seed(0)

a4 = np.random.randint(10 , size=(2,3,3))
a4

array([[[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2]],

       [[4, 7, 6],
        [8, 8, 1],
        [6, 7, 7]]])

In [43]:
a4.shape

(2, 3, 3)

In [44]:
a2_reshape = a2.reshape(2,3,1)
a2_reshape

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [45]:
a2.shape

(2, 3)

In [46]:
a2_reshape * a4

array([[[ 5. ,  0. ,  3. ],
        [ 6. , 14. , 18. ],
        [ 9.9, 16.5,  6.6]],

       [[16. , 28. , 24. ],
        [40. , 40. ,  5. ],
        [39. , 45.5, 45.5]]])

## Dot product

In [47]:
np.random.seed(0)
mat1 = np.random.randint(10 , size = (5,3))
mat2 = np.random.randint(10 , size =(5,3))

mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [48]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [49]:
mat2.T

array([[6, 8, 9, 4, 3],
       [7, 1, 8, 3, 5],
       [7, 5, 9, 0, 0]])

In [50]:
mat2.T.shape

(3, 5)

In [51]:
mat3 = np.dot(mat1,mat2.T)

In [52]:
mat3

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

In [53]:
mat3.shape

(5, 5)

## Dot product example

In [54]:
np.random.seed(0)
# No. of jars sold
sales_amount = np.random.randint(20 , size=(5,3))
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [55]:
# Weekly sales dataframe
import pandas as pd
weekly_sales = pd.DataFrame(sales_amount,
                            index = ["Mon","Tue","Wed","Thu","Fri"],
                            columns = ["Almond Butter","Peanut Butter","Cashew Butter"])
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon             12             15              0
Tue              3              3              7
Wed              9             19             18
Thu              4              6             12
Fri              1              6              7

In [56]:
prices = np.array([10 ,8 ,12])
prices

array([10,  8, 12])

In [57]:
prices.shape

(3,)

In [58]:
prices.T.shape

(3,)

In [59]:
butter_prices = pd.DataFrame(prices.reshape(1,3),
                             index = ["Prices"],
                             columns = ["Almond Butter","Peanut Butter","Cashew Butter"])
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Prices             10              8             12

In [60]:
np.dot(sales_amount,prices)

array([240, 138, 458, 232, 142])

In [61]:
total_sales = prices.dot(sales_amount.T)
total_sales

array([240, 138, 458, 232, 142])

In [62]:
butter_prices.T.shape , weekly_sales.shape

((3, 1), (5, 3))

In [63]:
daily_sales = np.dot(weekly_sales,butter_prices.T)

In [64]:
daily_sales

array([[240],
       [138],
       [458],
       [232],
       [142]])

In [65]:
ds = pd.DataFrame(daily_sales)
ds

0
0  240
1  138
2  458
3  232
4  142

In [66]:
daily_sales = butter_prices.dot(weekly_sales.T)

In [67]:
daily_sales

Mon  Tue  Wed  Thu  Fri
Prices  240  138  458  232  142

In [68]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon             12             15              0
Tue              3              3              7
Wed              9             19             18
Thu              4              6             12
Fri              1              6              7

In [69]:
weekly_sales["Total ($)"] = daily_sales.T

In [70]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter  Total ($)
Mon             12             15              0        240
Tue              3              3              7        138
Wed              9             19             18        458
Thu              4              6             12        232
Fri              1              6              7        142

## Sorting arrays

In [71]:
random_array

array([[3, 6, 6, 0],
       [9, 8, 4, 7],
       [0, 0, 7, 1]])

In [72]:
np.sort(random_array)

array([[0, 3, 6, 6],
       [4, 7, 8, 9],
       [0, 0, 1, 7]])

In [73]:
np.argsort(random_array)

array([[3, 0, 1, 2],
       [2, 3, 1, 0],
       [0, 1, 3, 2]], dtype=int64)

## Practical Example - Numpy in action!!

<img src = "panda_img.jpg"/>

In [93]:
# Turn an image into numpy array
from matplotlib.image import imread

panda = imread("panda_img.jpg")
print(type(panda))

<class 'numpy.ndarray'>


In [88]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)

In [95]:
panda[:2]

array([[[14, 27, 18],
        [14, 27, 18],
        [14, 27, 18],
        ...,
        [42, 35, 25],
        [42, 35, 25],
        [42, 35, 25]],

       [[14, 27, 18],
        [14, 27, 18],
        [14, 27, 18],
        ...,
        [42, 35, 25],
        [42, 35, 25],
        [42, 35, 25]]], dtype=uint8)